spring:
  application:
    name: lifeonhana

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lifeonhana_localDB
    username: LifeOnHana
    password: LifeOnHana1!

  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
    generate-ddl: true

  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 2000
      database: 0
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 2000ms


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.example.lifeonhana: debug

server:
  port: 8080
